In [1]:
import pandas as pd

In [24]:
# data collect from this website https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_population
data1=pd.read_excel("population.xlsx")

In [32]:
data1

,Rank,STATE/UT,Population[18][19],National Share (%),Decadal growth,Rural population,Percent rural,Urban population,Percent urban,Population Density[a],Sex ratio
0,1 (S1),Uttar Pradesh,199812341,0.1651,0.202,155317278,0.7773,44495063,0.2227,"828/km2 (2,140/sq mi)",912
1,2 (S2),Maharashtra,112374333,0.0928,0.16,61556074,0.5478,50818259,0.4522,365/km2 (950/sq mi),929
2,3 (S3),Bihar,104099452,0.0860,0.254,92341436,0.8871,11758016,0.1129,"1,102/km2 (2,850/sq mi)",918
3,4 (S4),West Bengal,91276115,0.0754,0.138,62183113,0.6813,29093002,0.3187,"1,029/km2 (2,670/sq mi)",953
4,5 (S5),Madhya Pradesh,72626809,0.0600,0.203,52557404,0.7237,20069405,0.2763,236/km2 (610/sq mi),931
5,6 (S6),Tamil Nadu,72147030,0.0596,0.156,37229590,0.5160,34917440,0.4840,"555/km2 (1,440/sq mi)",996
6,7 (S7),Rajasthan,68548437,0.0566,0.213,51500352,0.7513,17048085,0.2487,201/km2 (520/sq mi),928
7,8 (S8),Karnataka,61095297,0.0505,0.156,37469335,0.6133,23625962,0.3867,319/km2 (830/sq mi),973
8,9 (S9),Gujarat,60439692,0.0499,0.193,34694609,0.5740,25745083,0.4260,308/km2 (800/sq mi),919
9,10 (S10),Andhra Pradesh,"49,577,103[b]",0.0410,0.11,34966693,0.7053,14610410,0.2947,303/km2 (780/sq mi),993
10,11 (S11),Odisha,41974219,0.0347,0.14,34970562,0.8331,7003656,0.1669,269/km2 (700/sq mi),979
11,12 (S12),Telangana,35003674,0.0289,0.1358,21395009,0.6112,13608665,0.3888,312/km2 (810/sq mi),988
12,13 (S13),Kerala,33406061,0.0276,0.049,17471135,0.5230,15934926,0.4770,"859/km2 (2,220/sq mi)",1084
13,14 (S14),Jharkhand,32988134,0.0273,0.224,25055073,0.7595,7933061,0.2405,"414/km2 (1,070/sq mi)",948
14,15 (S15),Assam,31205576,0.0258,0.171,26807034,0.8590,4398542,0.1410,"398/km2 (1,030/sq mi)",958
15,16 (S16),Punjab,27743338,0.0229,0.1389,17344192,0.6252,10399146,0.3748,"551/km2 (1,430/sq mi)",895
16,17 (S17),Chhattisgarh,25545198,0.0211,0.226,19607961,0.7676,5937237,0.2324,189/km2 (490/sq mi),991
17,18 (S18),Haryana,25351462,0.0209,0.199,16509359,0.6512,8842103,0.3488,"573/km2 (1,480/sq mi)",879
18,19 (UT1),NCT of Delhi,16787941,0.0139,0.212,419042,0.0250,16368899,0.9750,"11,297/km2 (29,260/sq mi)",868
19,20 (UT2),Jammu and Kashmir,12267032,0.0101,0.236,9064220,0.7389,3202812,0.2611,297/km2 (770/sq mi),890
20,21 (S19),Uttarakhand,10086292,0.0083,0.188,7036954,0.6977,3049338,0.3023,189/km2 (490/sq mi),963
21,22 (S20),Himachal Pradesh,6864602,0.0057,0.129,6176050,0.8997,688552,0.1003,123/km2 (320/sq mi),972
22,23 (S21),Tripura,3673917,0.0030,0.148,2712464,0.7383,961453,0.2617,350/km2 (910/sq mi),960
23,24 (S22),Meghalaya,2966889,0.0025,0.279,2371439,0.7993,595450,0.2007,132/km2 (340/sq mi),989
24,25 (S23),Manipur[c],2570390,0.0021,0.245,1793875,0.6979,776515,0.3021,122/km2 (320/sq mi),992
25,26 (S24),Nagaland,1978502,0.0016,−0.6%,1407536,0.7114,570966,0.2886,119/km2 (310/sq mi),931
26,27 (S25),Goa,1458545,0.0012,0.082,551731,0.3783,906814,0.6217,"394/km2 (1,020/sq mi)",973
27,28 (S26),Arunachal Pradesh,1383727,0.0011,0.26,1066358,0.7706,317369,0.2294,17/km2 (44/sq mi),938
28,29 (UT3),Puducherry,1247953,0.0010,0.281,395200,0.3167,852753,0.6833,"2,598/km2 (6,730/sq mi)",1037
29,30 (S27),Mizoram,1097206,0.0009,0.235,525435,0.4789,571771,0.5211,52/km2 (130/sq mi),976
30,31 (UT4),Chandigarh,1055450,0.0009,0.172,28991,0.0275,1026459,0.9725,"9,252/km2 (23,960/sq mi)",818
31,32 (S28),Sikkim,610577,0.0005,0.129,456999,0.7485,153578,0.2515,86/km2 (220/sq mi),890
32,33 (UT5),Dadra and Nagar Haveli and Daman and Diu,585764,0.0005,0.551,243510,0.4157,342254,0.5843,"970/km2 (2,500/sq mi)",711
33,34 (UT6),Andaman and Nicobar Islands,380581,0.0003,0.069,237093,0.6230,143488,0.3770,46/km2 (120/sq mi),876
34,35 (UT7),Ladakh,274000,0.0002,0.178,43840,0.1600,230160,0.8400,2.8/km2 (7.3/sq mi),853
35,36 (UT8),Lakshadweep,64473,0.0001,0.063,14141,0.2193,50332,0.7807,"2,013/km2 (5,210/sq mi)",946
36,Total,India,1210569573,1.0000,0.177,833463448,0.6884,377106125,0.3116,382/km2 (990/sq mi),940

In [33]:

# Extract the state and population columns
state_population = data1[['STATE/UT', 'Population[18][19]']]

# Print the state and population information
print(state_population)

                                    STATE/UT Population[18][19]
0                              Uttar Pradesh          199812341
1                                Maharashtra          112374333
2                                      Bihar          104099452
3                                West Bengal           91276115
4                             Madhya Pradesh           72626809
5                                 Tamil Nadu           72147030
6                                  Rajasthan           68548437
7                                  Karnataka           61095297
8                                    Gujarat           60439692
9                             Andhra Pradesh      49,577,103[b]
10                                    Odisha           41974219
11                                 Telangana           35003674
12                                    Kerala           33406061
13                                 Jharkhand           32988134
14                                     Assam           31205576
15                                    Punjab           27743338
16                              Chhattisgarh           25545198
17                                   Haryana           25351462
18                              NCT of Delhi           16787941
19                         Jammu and Kashmir           12267032
20                               Uttarakhand           10086292
21                          Himachal Pradesh            6864602
22                                   Tripura            3673917
23                                 Meghalaya            2966889
24                                Manipur[c]            2570390
25                                  Nagaland            1978502
26                                       Goa            1458545
27                         Arunachal Pradesh            1383727
28                                Puducherry            1247953
29                                   Mizoram            1097206
30                                Chandigarh            1055450
31                                    Sikkim             610577
32  Dadra and Nagar Haveli and Daman and Diu             585764
33               Andaman and Nicobar Islands             380581
34                                    Ladakh             274000
35                               Lakshadweep              64473
36                                     India         1210569573

In [34]:
#https://www.findeasy.in/indian-states-by-literacy-rate/
data2=pd.read_excel("lit2.xlsx")
data2

                             STATE/UT  Literacy Rate
0                              Kerala         0.9400
1                          Chandigarh         0.8600
2                         Maharashtra         0.8230
3                         Uttarakhand         0.7880
4                         West Bengal         0.7630
5                             Haryana         0.7560
6                           Meghalaya         0.7440
7                      Madhya Pradesh         0.6930
8                   Jammu and Kashmir         0.6720
9                           Jharkhand         0.6640
10                              Bihar         0.6180
11                              Delhi         0.8620
12                   Himachal Pradesh         0.8280
13                         Tamil Nadu         0.8010
14                             Gujrat         0.7800
15                             Punjab         0.7580
16                          Karnataka         0.7540
17                       Chhattisgarh         0.7030
18                      Uttar Pradesh         0.6770
19                     Andhra Pradesh         0.6700
20                          Rajasthan         0.6610
21                                NaN            NaN
22                   Andaman &nicobar         0.8663
23                         chandigarh         0.8677
24  Dadar and nagar haveli Daman &Diu         0.8710
25                              Delhi         0.8621
26                                J&K         0.6716
27                             Ladakh         0.9029
28                        Lakshadweep         0.9185
29                         Puducherry         0.8585

In [35]:
# Extract the state and literacy rate columns
state_literacy_rate = data2[['STATE/UT', 'Literacy Rate']]

# Remove any NaN values
state_literacy_rate = state_literacy_rate.dropna()

# Print the state and literacy rate information
print(state_literacy_rate)

                             STATE/UT  Literacy Rate
0                              Kerala         0.9400
1                          Chandigarh         0.8600
2                         Maharashtra         0.8230
3                         Uttarakhand         0.7880
4                         West Bengal         0.7630
5                             Haryana         0.7560
6                           Meghalaya         0.7440
7                      Madhya Pradesh         0.6930
8                   Jammu and Kashmir         0.6720
9                           Jharkhand         0.6640
10                              Bihar         0.6180
11                              Delhi         0.8620
12                   Himachal Pradesh         0.8280
13                         Tamil Nadu         0.8010
14                             Gujrat         0.7800
15                             Punjab         0.7580
16                          Karnataka         0.7540
17                       Chhattisgarh         0.7030
18                      Uttar Pradesh         0.6770
19                     Andhra Pradesh         0.6700
20                          Rajasthan         0.6610
22                   Andaman &nicobar         0.8663
23                         chandigarh         0.8677
24  Dadar and nagar haveli Daman &Diu         0.8710
25                              Delhi         0.8621
26                                J&K         0.6716
27                             Ladakh         0.9029
28                        Lakshadweep         0.9185
29                         Puducherry         0.8585